
# Practice Assignment

# Feature Engineering, Machine Learning Development and Ray

---

## Learning Outcomes

After completing this notebook students should be able to:

1. Handle missing values
2. Remove duplicates
3. Detect outliers
4. Perform scaling
5. Perform normalization
6. Encode categorical variables
7. Create derived features
8. Create temporal features
9. Build Scikit-Learn Pipelines
10. Understand Ray Architecture
11. Create Remote Functions
12. Use Ray Tasks
13. Use Actors
14. Work with Ray Data
15. Build Ray Train workflows
16. Perform Hyperparameter Tuning with Ray Tune
17. Deploy Models using Ray Serve

---

### Instructions

- Attempt all TODO sections first.
- Use hints when needed.
- View solutions only after attempting.


# Exercise 1: Install Required Libraries

## Background


A Machine Learning Engineer is setting up a new
development environment.

Required libraries must be installed before
building ML pipelines.


## Dataset / Input


Libraries

1. pandas
2. scikit-learn
3. ray


## Task


Install the required libraries.


## Hint


Use pip install.

In [75]:

# =====================================================
# TODO
# =====================================================


# Install libraries


## Solution

In [76]:

!pip install pandas
!pip install scikit-learn
!pip install ray[default]

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: ray[default] in /usr/local/lib/python3.12/dist-packages (2.55.1)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from ray[default]) (8.4.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from ray[default]) (3.29.2)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from ray[default]) (4.26.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ray[default]) (1.1.2)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from ray[default]) (26.2)
Requirement already satisfied: protobuf>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from ray[default]) (5.29.6)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from ray[default]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from ray[default]) (2.32.4)
Requirement already satisfied: aiohttp>=3.13.3 in /usr/local/lib/python3.12/dist-packages (from ray[default]) (3.14.1)
Requirement already satisfied: aiohttp_cors in /usr/local/lib/python3.12/dist-packages (from ray[default]) (0.8.1)
Requirement already satisfied: colorful in /usr/local/lib/python3.12/dist-packages (from ray[default]) (0.5.8)
Requirement already satisfied: py-spy>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from ray[default]) (0.4.2)
Requirement already satisfied: grpcio>=1.42.0 in /usr/local/lib/python3.12/dist-packages (from ray[default]) (1.81.0)
Requirement already satisfied: opencensus in /usr/local/lib/python3.12/dist-packages (from ray[default]) (0.11.4)
Requirement already satisfied: opentelemetry-sdk>=1.30.0 in /usr/local/lib/python3.12/dist-packages (from ray[default]) (1.38.0)
Requirement already satisfied: opentelemetry-exporter-prometheus in /usr/local/lib/python3.12/dist-packages (from ray[default]) (0.59b0)
Requirement already satisfied: opentelemetry-proto in /usr/local/lib/python3.12/dist-packages (from ray[default]) (1.38.0)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3 in /usr/local/lib/python3.12/dist-packages (from ray[default]) (2.12.3)
Requirement already satisfied: prometheus_client>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from ray[default]) (0.25.0)
Requirement already satisfied: smart_open in /usr/local/lib/python3.12/dist-packages (from ray[default]) (7.6.1)
Requirement already satisfied: virtualenv!=20.21.1,>=20.0.24 in /usr/local/lib/python3.12/dist-packages (from ray[default]) (21.5.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->ray[default]) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->ray[default]) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->ray[default]) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->ray[default]) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->ray[default]) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->ray[default]) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->ray[default]) (4.15.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->ray[default]) (1.24.2)
Requirement already satisfied: opentelemetry-api==1.38.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.30.0->ray[default]) (1.38.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.30.0->ray[default]) (0.59b0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api==1.38.0->opentelemetry-sdk>=1.30.0->ray[default]) (8.7.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[default]) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[default]) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[default]) (0.4.2)
Requirement already satisfied: distlib<1,>=0.3.7 in /usr/local/lib/python3.12/dist-packages (from virtualenv!=20.21.1,>=20.0.24->ray[default]) (0.4.3)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from virtualenv!=20.21.1,>=20.0.24->ray[default]) (4.10.0)
Requirement already satisfied: python-discovery>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from virtualenv!=20.21.1,>=20.0.24->ray[default]) (1.4.2)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray[default]) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray[default]) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray[default]) (2026.5.1)
Requirement already satisfied: opencensus-context>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from opencensus->ray[default]) (0.1.3)
Requirement already satisfied: six~=1.16 in /usr/local/lib/python3.12/dist-packages (from opencensus->ray[default]) (1.17.0)
Requirement already satisfied: google-api-core<3.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from opencensus->ray[default]) (2.30.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->ray[default]) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->ray[default]) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->ray[default]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->ray[default]) (2026.5.20)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open->ray[default]) (2.2.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (1.75.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (1.28.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (2.47.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (4.9.1)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api==1.38.0->opentelemetry-sdk>=1.30.0->ray[default]) (4.1.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (0.6.3)

Background

A telecom company collected customer information from multiple sources.
Some records have missing values because customers skipped fields during registration.

Dataset / Input

The DataFrame df contains:

| age | monthly_bill | city |
|------|------|------|
| 25 | 300 | Chennai |
| 30 | 500 | Delhi |
| NaN | 450 | Delhi |
| 40 | NaN | Mumbai |
| 35 | 700 | Chennai |

Task

Replace missing values as follows:

1. Replace missing values in age using the mean of the age column.
2. Replace missing values in monthly_bill using the mean of the monthly_bill column.
3. Store the updated values back into df.

Expected Result

The DataFrame should contain no missing values in age and monthly_bill.


# Exercise 2: Import Libraries

## Background


Most ML workflows begin by importing
required libraries.


## Dataset / Input


Libraries

pandas
numpy
ray


## Task


Import required libraries.


## Hint


Use import statements.

In [77]:

# =====================================================
# TODO
# =====================================================


# Import libraries


## Solution

In [78]:

import pandas as pd
import numpy as np
import ray

print("Libraries Imported")

Libraries Imported


# Feature Engineering

In this section we will build a customer
analytics dataset and perform feature
engineering operations.


# Exercise 3: Create Customer Dataset

## Background


A telecom company stores customer records.

The dataset will be reused throughout
the notebook.


## Dataset / Input


Customer Information


## Task


Create a Pandas DataFrame.


## Hint


Use pd.DataFrame().

In [79]:

# =====================================================
# TODO
# =====================================================


# Create DataFrame


## Solution

In [80]:

import pandas as pd

df = pd.DataFrame({

    "age":[25,30,None,40,35],

    "monthly_bill":[300,500,450,None,700],

    "city":[
        "Chennai",
        "Delhi",
        "Delhi",
        "Mumbai",
        "Chennai"
    ]
})

df

    age  monthly_bill     city
0  25.0         300.0  Chennai
1  30.0         500.0    Delhi
2   NaN         450.0    Delhi
3  40.0           NaN   Mumbai
4  35.0         700.0  Chennai


# Exercise 4: Handle Missing Values

## Background


Some customer records contain missing values.

Models cannot train reliably with missing data.


## Dataset / Input


Customer Dataset


## Task


Replace missing values using mean imputation.


## Hint


Use fillna().

In [81]:

# =====================================================
# TODO
# =====================================================


# Handle missing values


## Solution

In [82]:

df["age"] = df["age"].fillna(
    df["age"].mean()
)

df["monthly_bill"] = df["monthly_bill"].fillna(
    df["monthly_bill"].mean()
)

df

    age  monthly_bill     city
0  25.0         300.0  Chennai
1  30.0         500.0    Delhi
2  32.5         450.0    Delhi
3  40.0         487.5   Mumbai
4  35.0         700.0  Chennai


# Exercise 5: Remove Duplicates

## Background


Duplicate records may distort analysis.


## Dataset / Input


Customer Dataset


## Task


Remove duplicate rows.


## Hint


Use drop_duplicates().

In [83]:

# =====================================================
# TODO
# =====================================================


# Remove duplicates


## Solution

In [84]:

df = df.drop_duplicates()

df

    age  monthly_bill     city
0  25.0         300.0  Chennai
1  30.0         500.0    Delhi
2  32.5         450.0    Delhi
3  40.0         487.5   Mumbai
4  35.0         700.0  Chennai


# Exercise 6: Detect Outliers

## Background


Management suspects unusually high bills.


## Dataset / Input


monthly_bill column


## Task


Identify outliers using IQR.


## Hint


Use quantiles.

In [85]:

# =====================================================
# TODO
# =====================================================


# Detect outliers


## Solution

In [86]:

q1 = df["monthly_bill"].quantile(0.25)
q3 = df["monthly_bill"].quantile(0.75)

iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

outliers = df[
    (df["monthly_bill"] < lower)
    |
    (df["monthly_bill"] > upper)
]

outliers

    age  monthly_bill     city
0  25.0         300.0  Chennai
4  35.0         700.0  Chennai


# Exercise 7: Standard Scaling

## Background


Features should often be scaled before
model training.


## Dataset / Input


age
monthly_bill


## Task


Apply StandardScaler.


## Hint


Use StandardScaler.

In [87]:

# =====================================================
# TODO
# =====================================================


# Scale features


## Solution

In [88]:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled = scaler.fit_transform(

    df[
        [
            "age",
            "monthly_bill"
        ]
    ]

)

scaled

array([[-1.5       , -1.46524625],
       [-0.5       ,  0.09768308],
       [ 0.        , -0.29304925],
       [ 1.5       ,  0.        ],
       [ 0.5       ,  1.66061241]])


# Exercise 8: Min Max Normalization

## Background


Some algorithms require values between
0 and 1.


## Dataset / Input


age
monthly_bill


## Task


Apply MinMaxScaler.


## Hint


Use MinMaxScaler.

In [89]:

# =====================================================
# TODO
# =====================================================


# Normalize features


## Solution

In [90]:

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

normalized = scaler.fit_transform(

    df[
        [
            "age",
            "monthly_bill"
        ]
    ]

)

normalized

array([[0.        , 0.        ],
       [0.33333333, 0.5       ],
       [0.5       , 0.375     ],
       [1.        , 0.46875   ],
       [0.66666667, 1.        ]])


# Exercise 9: Label Encoding

## Background


Machine learning models require
numerical features.


## Dataset / Input


city column


## Task


Encode city values.


## Hint


Use LabelEncoder.

In [91]:

# =====================================================
# TODO
# =====================================================


# Encode city


## Solution

In [92]:

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["city_encoded"] = encoder.fit_transform(
    df["city"]
)

df

    age  monthly_bill     city  city_encoded
0  25.0         300.0  Chennai             0
1  30.0         500.0    Delhi             1
2  32.5         450.0    Delhi             1
3  40.0         487.5   Mumbai             2
4  35.0         700.0  Chennai             0


# Exercise 10: One Hot Encoding

## Background


Categorical variables can also be
represented using one-hot encoding.


## Dataset / Input


city column


## Task


Create one-hot encoded features.


## Hint


Use get_dummies().

In [93]:

# =====================================================
# TODO
# =====================================================


# One hot encode


## Solution

In [94]:

encoded = pd.get_dummies(
    df,
    columns=["city"]
)

encoded

    age  monthly_bill  city_encoded  city_Chennai  city_Delhi  city_Mumbai
0  25.0         300.0             0          True       False        False
1  30.0         500.0             1         False        True        False
2  32.5         450.0             1         False        True        False
3  40.0         487.5             2         False       False         True
4  35.0         700.0             0          True       False        False


# Exercise 11: Create Derived Features

## Background


Revenue analysts want yearly billing.


## Dataset / Input


monthly_bill


## Task


Create annual_bill feature.


## Hint


Multiply by 12.

In [95]:

# =====================================================
# TODO
# =====================================================


# Create feature


## Solution

In [96]:

df["annual_bill"] = (
    df["monthly_bill"] * 12
)

df

    age  monthly_bill     city  city_encoded  annual_bill
0  25.0         300.0  Chennai             0       3600.0
1  30.0         500.0    Delhi             1       6000.0
2  32.5         450.0    Delhi             1       5400.0
3  40.0         487.5   Mumbai             2       5850.0
4  35.0         700.0  Chennai             0       8400.0


# Exercise 12: Create Temporal Features

## Background


Customer transactions contain dates.


## Dataset / Input


transaction_date


## Task


Extract month feature.


## Hint


Use pd.to_datetime().

In [97]:

# =====================================================
# TODO
# =====================================================


# Extract month


## Solution

In [98]:

df["transaction_date"] = pd.to_datetime(
    [
        "2025-01-01",
        "2025-02-03",
        "2025-03-15",
        "2025-04-21",
        "2025-05-12"
    ]
)

df["month"] = (
    df["transaction_date"]
    .dt.month
)

df

,age,monthly_bill,city,city_encoded,annual_bill,transaction_date,month
0,25.0,300.0,Chennai,0,3600.0,2025-01-01,1
1,30.0,500.0,Delhi,1,6000.0,2025-02-03,2
2,32.5,450.0,Delhi,1,5400.0,2025-03-15,3
3,40.0,487.5,Mumbai,2,5850.0,2025-04-21,4
4,35.0,700.0,Chennai,0,8400.0,2025-05-12,5


# Exercise 13: Train Validation Test Split

## Background


Models should be evaluated properly.


## Dataset / Input


Customer Dataset


## Task


Create train and test splits.


## Hint


Use train_test_split().

In [99]:

# =====================================================
# TODO
# =====================================================


# Split dataset


## Solution

In [100]:

from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(

    df,

    test_size=0.2,

    random_state=42

)

print(len(train_df))
print(len(test_df))

4
1


# Exercise 14: Scikit Learn Pipeline

## Background


Preprocessing and model training should
be reproducible.


## Dataset / Input


Customer Dataset


## Task


Create a pipeline.


## Hint


Use Pipeline().

In [101]:

# =====================================================
# TODO
# =====================================================


# Create pipeline


## Solution

In [102]:

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline(

    [

        (
            "scaler",
            StandardScaler()
        ),

        (
            "model",
            LogisticRegression()
        )

    ]

)

pipeline

Pipeline(steps=[('scaler', StandardScaler()), ('model', LogisticRegression())])


# Ray Core

In this section we will learn Ray
through practical exercises.


# Exercise 15: Initialize Ray

## Background


Ray must be initialized before use.


## Dataset / Input


No Dataset


## Task


Start a local Ray runtime.


## Hint


Use ray.init().

In [103]:

# =====================================================
# TODO
# =====================================================


# Initialize Ray


## Solution

In [104]:

import ray

ray.init(ignore_reinit_error=True)

2026-06-16 19:34:25,495	INFO worker.py:1828 -- Calling ray.init() again after it has already been called.

RayContext(dashboard_url='127.0.0.1:8265', python_version='3.12.13', ray_version='2.55.1', ray_commit='237c2455ebb1ea15a32dd9e1fdeb2d617badc37f')


# Exercise 16: Create Remote Function

## Background


A company wants distributed execution.


## Dataset / Input


Numbers


## Task


Create a remote function.


## Hint


Use @ray.remote.

In [105]:

# =====================================================
# TODO
# =====================================================


# Create remote function


## Solution

In [106]:

@ray.remote
def square(x):

    return x * x

result = ray.get(
    square.remote(5)
)

print(result)

25


# Exercise 17: Parallel Tasks

## Background


Many tasks should run simultaneously.


## Dataset / Input


Numbers 1-10


## Task


Execute tasks in parallel.


## Hint


Use .remote().

In [107]:

# =====================================================
# TODO
# =====================================================


# Parallel tasks


## Solution

In [108]:

@ray.remote
def square(x):
    return x * x

futures = [

    square.remote(i)

    for i in range(10)

]

results = ray.get(
    futures
)

print(results)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


# Exercise 18: Using ray.wait

## Background


Some tasks finish before others.


## Dataset / Input


Tasks


## Task


Wait for first completed task.


## Hint


Use ray.wait().

In [109]:

# =====================================================
# TODO
# =====================================================


# Wait for tasks


## Solution

In [110]:

import time

@ray.remote
def work(x):

    time.sleep(x)

    return x

tasks = [

    work.remote(i)

    for i in [3,1,2]

]

ready, pending = ray.wait(
    tasks,
    num_returns=1
)

print(ray.get(ready))

[1]


# Exercise 19: Create Actor

## Background


Some applications require state.


## Dataset / Input


Counter Example


## Task


Create an Actor.


## Hint


Use class + @ray.remote.

In [111]:

# =====================================================
# TODO
# =====================================================


# Create actor


## Solution

In [112]:

@ray.remote
class Counter:

    def __init__(self):

        self.count = 0

    def increment(self):

        self.count += 1

        return self.count

counter = Counter.remote()

print(
    ray.get(
        counter.increment.remote()
    )
)

1


# Exercise 20: Stateful Actor

## Background


Actors maintain state between calls.


## Dataset / Input


Counter


## Task


Increment counter multiple times.


## Hint


Call actor methods repeatedly.

In [113]:

# =====================================================
# TODO
# =====================================================


# Increment actor


## Solution

In [114]:

@ray.remote
class Counter:

    def __init__(self):

        self.count = 0

    def increment(self):

        self.count += 1

        return self.count

counter = Counter.remote()

for _ in range(5):

    print(
        ray.get(
            counter.increment.remote()
        )
    )

1
2
3
4
5


# Ray Data

Ray Data provides scalable datasets
for machine learning and analytics.


# Exercise 21: Create Ray Dataset

## Background


An analytics team wants to process
customer records using Ray Data.


## Dataset / Input


Customer Records


## Task


Create a Ray Dataset.


## Hint


Use ray.data.from_items().

In [115]:

# =====================================================
# TODO
# =====================================================


# Create Dataset


## Solution

In [116]:

import ray
import ray.data

dataset = ray.data.from_items(

    [

        {
            "customer":"A",
            "bill":300
        },

        {
            "customer":"B",
            "bill":500
        },

        {
            "customer":"C",
            "bill":700
        }

    ]

)

dataset.show()

2026-06-16 19:34:47,731	INFO logging.py:416 -- Registered dataset logger for dataset dataset_17_0
2026-06-16 19:34:47,744	INFO streaming_executor.py:166 -- Starting execution of Dataset dataset_17_0. Full logs are in /tmp/ray/session_2026-06-16_19-24-29_344446_7231/logs/ray-data
2026-06-16 19:34:47,749	INFO streaming_executor.py:167 -- Execution plan of Dataset dataset_17_0: InputDataBuffer[Input] -> LimitOperator[limit=20]
2026-06-16 19:34:47,860	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_17_0 =======
2026-06-16 19:34:47,865	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-06-16 19:34:47,869	INFO logging_progress.py:227 -- Active & requested resources: 0/2 CPU, 0.0B/1.9GiB object store
2026-06-16 19:34:47,875	INFO logging_progress.py:181 --
2026-06-16 19:34:47,879	INFO logging_progress.py:231 -- limit=20: 0/1
2026-06-16 19:34:47,884	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 2 (0.0B); Resources: 0.0 CPU, 13.0B object store
2026-06-16 19:34:47,886	INFO logging_progress.py:192 -- =============================================
2026-06-16 19:34:47,923	INFO streaming_executor.py:294 -- ✔️  Dataset dataset_17_0 execution finished in 0.18 seconds

{'customer': 'A', 'bill': 300}
{'customer': 'B', 'bill': 500}
{'customer': 'C', 'bill': 700}


# Exercise 22: Map Transformation

## Background


Management wants yearly billing
for every customer.


## Dataset / Input


Customer Dataset


## Task


Create annual_bill.


## Hint


Use map().

In [117]:

# =====================================================
# TODO
# =====================================================


# Map Dataset


## Solution

In [118]:

dataset = ray.data.from_items(

    [

        {"bill":300},
        {"bill":500},
        {"bill":700}

    ]

)

dataset = dataset.map(

    lambda row: {

        **row,

        "annual_bill":
        row["bill"] * 12

    }

)

dataset.show()

2026-06-16 19:34:48,149	INFO logging.py:416 -- Registered dataset logger for dataset dataset_20_0
2026-06-16 19:34:48,164	INFO streaming_executor.py:166 -- Starting execution of Dataset dataset_20_0. Full logs are in /tmp/ray/session_2026-06-16_19-24-29_344446_7231/logs/ray-data
2026-06-16 19:34:48,168	INFO streaming_executor.py:167 -- Execution plan of Dataset dataset_20_0: InputDataBuffer[Input] -> LimitOperator[limit=20] -> TaskPoolMapOperator[Map(<lambda>)]
2026-06-16 19:34:48,251	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_20_0 =======
2026-06-16 19:34:48,253	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-06-16 19:34:48,254	INFO logging_progress.py:227 -- Active & requested resources: 0/2 CPU, 0.0B/1.9GiB object store
2026-06-16 19:34:48,255	INFO logging_progress.py:181 --
2026-06-16 19:34:48,255	INFO logging_progress.py:231 -- limit=20: 0/1
2026-06-16 19:34:48,256	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 2 (0.0B); Resources: 0.0 CPU, 8.0B object store
2026-06-16 19:34:48,256	INFO logging_progress.py:231 -- Map(<lambda>): 0/1
2026-06-16 19:34:48,260	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 0 (0.0B); Resources: 0.0 CPU, 0.0B object store
2026-06-16 19:34:48,263	INFO logging_progress.py:192 -- =============================================
2026-06-16 19:34:52,075	INFO streaming_executor.py:294 -- ✔️  Dataset dataset_20_0 execution finished in 3.91 seconds

{'bill': 300, 'annual_bill': 3600}
{'bill': 500, 'annual_bill': 6000}
{'bill': 700, 'annual_bill': 8400}


# Exercise 23: Filter Records

## Background


Marketing wants customers whose
monthly bill exceeds 400.


## Dataset / Input


Customer Dataset


## Task


Filter records.


## Hint


Use filter().

In [119]:

# =====================================================
# TODO
# =====================================================


# Filter Dataset


## Solution

In [120]:

dataset = ray.data.from_items(

    [

        {"bill":300},
        {"bill":500},
        {"bill":700}

    ]

)

filtered = dataset.filter(

    lambda row:
    row["bill"] > 400

)

filtered.show()

/usr/local/lib/python3.12/dist-packages/ray/data/dataset.py:1633: UserWarning: Use 'expr' instead of 'fn' when possible for performant filters.
  warnings.warn(
2026-06-16 19:34:52,152	INFO logging.py:416 -- Registered dataset logger for dataset dataset_23_0
2026-06-16 19:34:52,157	INFO streaming_executor.py:166 -- Starting execution of Dataset dataset_23_0. Full logs are in /tmp/ray/session_2026-06-16_19-24-29_344446_7231/logs/ray-data
2026-06-16 19:34:52,158	INFO streaming_executor.py:167 -- Execution plan of Dataset dataset_23_0: InputDataBuffer[Input] -> TaskPoolMapOperator[Filter(<lambda>)] -> LimitOperator[limit=20]
2026-06-16 19:34:52,191	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_23_0 =======
2026-06-16 19:34:52,197	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-06-16 19:34:52,199	INFO logging_progress.py:227 -- Active & requested resources: 0/2 CPU, 0.0B/1.9GiB object store
2026-06-16 19:34:52,201	INFO logging_progress.py:181 --
2026-06-16 19:34:52,205	INFO logging_progress.py:231 -- Filter(<lambda>): 0/1
2026-06-16 19:34:52,206	INFO logging_progress.py:233 --   Tasks: 1; Actors: 0; Queued blocks: 2 (0.0B); Resources: 1.0 CPU, 0.0B object store
2026-06-16 19:34:52,208	INFO logging_progress.py:231 -- limit=20: 0/1
2026-06-16 19:34:52,210	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 0 (0.0B); Resources: 0.0 CPU, 0.0B object store
2026-06-16 19:34:52,213	INFO logging_progress.py:192 -- =============================================
2026-06-16 19:34:52,279	INFO streaming_executor.py:294 -- ✔️  Dataset dataset_23_0 execution finished in 0.12 seconds

{'bill': 500}
{'bill': 700}


# Exercise 24: Dataset Aggregation

## Background


Finance wants total revenue.


## Dataset / Input


Bills

300
500
700


## Task


Compute total bill.


## Hint


Convert to pandas.

In [121]:

# =====================================================
# TODO
# =====================================================


# Aggregate Dataset


## Solution

In [122]:

dataset = ray.data.from_items(

    [

        {"bill":300},
        {"bill":500},
        {"bill":700}

    ]

)

pdf = dataset.to_pandas()

print(
    pdf["bill"].sum()
)

2026-06-16 19:34:52,332	INFO logging.py:416 -- Registered dataset logger for dataset dataset_24_0
2026-06-16 19:34:52,354	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_24_0 =======
2026-06-16 19:34:52,356	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-06-16 19:34:52,356	INFO logging_progress.py:227 -- Active & requested resources: 0/2 CPU, 0.0B/1.9GiB object store
2026-06-16 19:34:52,361	INFO logging_progress.py:192 -- =============================================
2026-06-16 19:34:52,380	INFO streaming_executor.py:294 -- ✔️  Dataset dataset_24_0 execution finished in 0.00 seconds

1500


# Exercise 25: Lazy Execution

## Background


Ray Data transformations are lazy.

Execution occurs only when the
dataset is consumed.


## Dataset / Input


Dataset


## Task


Create a transformation and
materialize it.


## Hint


Use show().

In [123]:

# =====================================================
# TODO
# =====================================================


# Lazy Execution


## Solution

In [124]:

dataset = ray.data.range(10)

dataset = dataset.map(

    lambda x: {
        "value":x["id"] * 2
    }

)

dataset.show()

2026-06-16 19:34:52,434	INFO logging.py:416 -- Registered dataset logger for dataset dataset_27_0
2026-06-16 19:34:52,446	INFO streaming_executor.py:166 -- Starting execution of Dataset dataset_27_0. Full logs are in /tmp/ray/session_2026-06-16_19-24-29_344446_7231/logs/ray-data
2026-06-16 19:34:52,447	INFO streaming_executor.py:167 -- Execution plan of Dataset dataset_27_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange] -> LimitOperator[limit=20] -> TaskPoolMapOperator[Map(<lambda>)]
2026-06-16 19:34:52,528	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_27_0 =======
2026-06-16 19:34:52,532	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-06-16 19:34:52,532	INFO logging_progress.py:227 -- Active & requested resources: 0/2 CPU, 0.0B/1.9GiB object store
2026-06-16 19:34:52,533	INFO logging_progress.py:181 --
2026-06-16 19:34:52,534	INFO logging_progress.py:231 -- ReadRange: 0/1
2026-06-16 19:34:52,535	INFO logging_progress.py:233 --   Tasks: 1; Actors: 0; Queued blocks: 4 (0.0B); Resources: 1.0 CPU, 0.0B object store
2026-06-16 19:34:52,536	INFO logging_progress.py:231 -- limit=20: 0/1
2026-06-16 19:34:52,537	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 0 (0.0B); Resources: 0.0 CPU, 0.0B object store
2026-06-16 19:34:52,538	INFO logging_progress.py:231 -- Map(<lambda>): 0/1
2026-06-16 19:34:52,538	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 0 (0.0B); Resources: 0.0 CPU, 0.0B object store
2026-06-16 19:34:52,539	INFO logging_progress.py:192 -- =============================================
2026-06-16 19:34:52,743	INFO streaming_executor.py:294 -- ✔️  Dataset dataset_27_0 execution finished in 0.30 seconds

{'value': 0}
{'value': 2}
{'value': 4}
{'value': 6}
{'value': 8}
{'value': 10}
{'value': 12}
{'value': 14}
{'value': 16}
{'value': 18}


# Ray Architecture

Driver
Workers
Actors
Object Store
Schedulers


# Exercise 26: Driver and Worker Concept

## Background


Ray applications consist of a Driver
and multiple Workers.


## Dataset / Input


No Dataset


## Task


Explain Driver and Worker roles.


## Hint


Think about task submission.

In [125]:

# =====================================================
# TODO
# =====================================================


# Write explanation


## Solution

In [126]:

print(

'''
Driver:

Runs user program.

Worker:

Executes remote tasks.

The Driver submits tasks
to Workers.
'''

)

Driver:

Runs user program.

Worker:

Executes remote tasks.

The Driver submits tasks
to Workers.


# Exercise 27: Object References

## Background


Ray stores results as object references.


## Dataset / Input


Number = 10


## Task


Create and retrieve an object ref.


## Hint


Use ray.put().

In [127]:

# =====================================================
# TODO
# =====================================================


# Create object ref


## Solution

In [128]:

obj_ref = ray.put(10)

value = ray.get(
    obj_ref
)

print(value)

10


# Ray Train

Ray Train enables distributed
model training.


# Exercise 28: Training Function

## Background


Distributed training begins with
a training function.


## Dataset / Input


No Dataset


## Task


Create train_func.


## Hint


Define a Python function.

In [129]:

# =====================================================
# TODO
# =====================================================


# Create train function


## Solution

In [130]:

def train_func():

    print(
        "Training Started"
    )

train_func()

Training Started


# Exercise 29: Scaling Configuration

## Background


Distributed training requires
resource allocation.


## Dataset / Input


No Dataset


## Task


Create ScalingConfig.


## Hint


Use ScalingConfig().

In [131]:

# =====================================================
# TODO
# =====================================================


# Create scaling config


## Solution

In [132]:

from ray.train import (
    ScalingConfig
)

config = ScalingConfig(

    num_workers=2,

    use_gpu=False

)

print(config)

ScalingConfig(trainer_resources=None, num_workers=2, use_gpu=False, resources_per_worker=None, placement_strategy='PACK', accelerator_type=None, label_selector=None, use_tpu=False, topology=None, elastic_resize_monitor_interval_s=60.0)


# Exercise 30: Trainer Creation

## Background


A Trainer manages distributed
worker execution.


## Dataset / Input


No Dataset


## Task


Create a Trainer.


## Hint


Use TorchTrainer.

In [133]:

# =====================================================
# TODO
# =====================================================


# Create trainer


## Solution

In [134]:

from ray.train.torch import (
    TorchTrainer
)

def train_func():

    print(
        "Worker Running"
    )

trainer = TorchTrainer(

    train_func,

    scaling_config=

    ScalingConfig(

        num_workers=1,

        use_gpu=False

    )

)

print(trainer)

<ray.train.v2.torch.torch_trainer.TorchTrainer object at 0x7cc8906976e0>


# Ray Tune

Ray Tune automates
hyperparameter tuning.


# Exercise 31: Grid Search

## Background


Data scientists want to test
multiple learning rates.


## Dataset / Input


Learning Rates


## Task


Create a grid search.


## Hint


Use tune.grid_search().

In [135]:

# =====================================================
# TODO
# =====================================================


# Grid Search


## Solution

In [136]:

from ray import tune

search_space = {

    "lr":

    tune.grid_search(

        [
            0.001,
            0.01,
            0.1
        ]

    )

}

print(search_space)

{'lr': {'grid_search': [0.001, 0.01, 0.1]}}


# Exercise 32: Objective Function

## Background


Tune evaluates configurations
using an objective function.


## Dataset / Input


Parameters


## Task


Create objective().


## Hint


Return a score.

In [137]:

# =====================================================
# TODO
# =====================================================


# Objective Function


## Solution

In [138]:

def objective(config):

    score = (
        config["x"] ** 2
    )

    return {

        "score":score

    }

print(
    objective(
        {"x":2}
    )
)

{'score': 4}


# Exercise 33: Run Tuner

## Background


Ray Tune executes trials
and selects the best result.


## Dataset / Input


Search Space


## Task


Run a tuner.


## Hint


Use tune.Tuner().

In [139]:

# =====================================================
# TODO
# =====================================================


# Run tuner


## Solution

In [140]:

from ray import tune

def objective(config):

    return {

        "score":

        config["a"] ** 2

    }

tuner = tune.Tuner(

    objective,

    param_space={

        "a":

        tune.grid_search(

            [1,2,3]

        )

    }

)

print(tuner)

<ray.tune.tuner.Tuner object at 0x7cc785851100>


# Ray Serve

Ray Serve provides scalable
model serving.


# Exercise 34: Simple Deployment

## Background


An ML team wants to deploy
an inference service.


## Dataset / Input


No Dataset


## Task


Create a deployment.


## Hint


Use @serve.deployment.

In [141]:

# =====================================================
# TODO
# =====================================================


# Create deployment


## Solution

In [142]:

from ray import serve

@serve.deployment

class Predictor:

    def __call__(self):

        return "Prediction"

print(
    Predictor
)

Deployment(name=Predictor)


# Exercise 35: Inference Request

## Background


Clients send requests to
deployed models.


## Dataset / Input


Input Data


## Task


Simulate inference.


## Hint


Call prediction logic.

In [143]:

# =====================================================
# TODO
# =====================================================


# Simulate inference


## Solution

In [144]:

def predict(x):

    return x * 2

print(
    predict(10)
)

20


# Exercise 36: Mini Project: Distributed Customer Analytics

## Background


You are working as a Machine
Learning Engineer.

Management wants customer
revenue analytics.

Build a distributed Ray workflow.


## Dataset / Input


customers =

[
    {"customer":"A","bill":300},
    {"customer":"B","bill":500},
    {"customer":"C","bill":700},
    {"customer":"D","bill":900}
]


## Task


Create a Ray Dataset.

1. Load data
2. Create annual_bill
3. Filter annual_bill > 6000
4. Display result


## Hint


Use Ray Data map()
and filter().

In [145]:

# =====================================================
# TODO
# =====================================================


# Complete project


## Solution

In [146]:

import ray
import ray.data

customers = [

    {"customer":"A","bill":300},
    {"customer":"B","bill":500},
    {"customer":"C","bill":700},
    {"customer":"D","bill":900}

]

dataset = ray.data.from_items(
    customers
)

dataset = dataset.map(

    lambda row: {

        **row,

        "annual_bill":

        row["bill"] * 12

    }

)

dataset = dataset.filter(

    lambda row:

    row["annual_bill"] > 6000

)

dataset.show()

2026-06-16 19:34:52,979	INFO logging.py:416 -- Registered dataset logger for dataset dataset_31_0
2026-06-16 19:34:52,985	INFO streaming_executor.py:166 -- Starting execution of Dataset dataset_31_0. Full logs are in /tmp/ray/session_2026-06-16_19-24-29_344446_7231/logs/ray-data
2026-06-16 19:34:52,985	INFO streaming_executor.py:167 -- Execution plan of Dataset dataset_31_0: InputDataBuffer[Input] -> TaskPoolMapOperator[Map(<lambda>)->Filter(<lambda>)] -> LimitOperator[limit=20]
2026-06-16 19:34:53,017	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_31_0 =======
2026-06-16 19:34:53,020	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-06-16 19:34:53,024	INFO logging_progress.py:227 -- Active & requested resources: 0/2 CPU, 0.0B/1.9GiB object store
2026-06-16 19:34:53,025	INFO logging_progress.py:181 --
2026-06-16 19:34:53,026	INFO logging_progress.py:231 -- Map(<lambda>)->Filter(<lambda>): 0/1
2026-06-16 19:34:53,027	INFO logging_progress.py:233 --   Tasks: 1; Actors: 0; Queued blocks: 3 (0.0B); Resources: 1.0 CPU, 0.0B object store
2026-06-16 19:34:53,029	INFO logging_progress.py:231 -- limit=20: 0/1
2026-06-16 19:34:53,029	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 0 (0.0B); Resources: 0.0 CPU, 0.0B object store
2026-06-16 19:34:53,030	INFO logging_progress.py:192 -- =============================================
2026-06-16 19:34:53,167	INFO streaming_executor.py:294 -- ✔️  Dataset dataset_31_0 execution finished in 0.18 seconds

{'customer': 'C', 'bill': 700, 'annual_bill': 8400}
{'customer': 'D', 'bill': 900, 'annual_bill': 10800}


# Exercise 37: Mini Project: Hyperparameter Search

## Background


You are training a churn
prediction model.

Management wants the best
hyperparameters.


## Dataset / Input


Search Space

learning_rate

0.001
0.01
0.1


## Task


Perform a Ray Tune search
and identify the best result.


## Hint


Use grid_search().

In [147]:

# =====================================================
# TODO
# =====================================================


# Complete tuning project


## Solution

In [148]:

from ray import tune

def objective(config):

    score = (

        config["lr"] - 0.01

    ) ** 2

    return {

        "score":score

    }

tuner = tune.Tuner(

    objective,

    param_space={

        "lr":

        tune.grid_search(

            [
                0.001,
                0.01,
                0.1
            ]

        )

    }

)

results = tuner.fit()

print(

    results.get_best_result(

        metric="score",

        mode="min"

    ).config

)

2026-06-16 19:34:53,209	WARNING callback.py:132 -- The TensorboardX logger cannot be instantiated because either TensorboardX or one of it's dependencies is not installed. Please make sure you have the latest version of TensorboardX installed: `pip install -U tensorboardx`

+------------------------------------------------------------------+
| Configuration for experiment     objective_2026-06-16_19-34-53   |
+------------------------------------------------------------------+
| Search algorithm                 BasicVariantGenerator           |
| Scheduler                        FIFOScheduler                   |
| Number of trials                 3                               |
+------------------------------------------------------------------+

View detailed results here: /root/ray_results/objective_2026-06-16_19-34-53

Trial status: 3 PENDING
Current time: 2026-06-16 19:34:53. Total running time: 0s
Logical resource usage: 2.0/2 CPUs, 0/0 GPUs
+------------------------------------------+
| Trial name              status        lr |
+------------------------------------------+
| objective_72905_00000   PENDING    0.001 |
| objective_72905_00001   PENDING    0.01  |
| objective_72905_00002   PENDING    0.1   |
+------------------------------------------+

Trial objective_72905_00001 started with configuration:
+---------------------------------------------+
| Trial objective_72905_00001 config          |
+---------------------------------------------+
| lr                                     0.01 |
+---------------------------------------------+

Trial objective_72905_00001 completed after 1 iterations at 2026-06-16 19:35:05. Total running time: 12s
+------------------------------------------------+
| Trial objective_72905_00001 result             |
+------------------------------------------------+
| checkpoint_dir_name                            |
| time_this_iter_s                       0.00044 |
| time_total_s                           0.00044 |
| training_iteration                           1 |
| score                                        0 |
+------------------------------------------------+

Trial objective_72905_00000 started with configuration:
+----------------------------------------------+
| Trial objective_72905_00000 config           |
+----------------------------------------------+
| lr                                     0.001 |
+----------------------------------------------+

Trial objective_72905_00000 completed after 1 iterations at 2026-06-16 19:35:05. Total running time: 12s
+------------------------------------------------+
| Trial objective_72905_00000 result             |
+------------------------------------------------+
| checkpoint_dir_name                            |
| time_this_iter_s                       0.00134 |
| time_total_s                           0.00134 |
| training_iteration                           1 |
| score                                    8e-05 |
+------------------------------------------------+

2026-06-16 19:35:14,134	INFO tune.py:1001 -- Wrote the latest version of all result files and experiment state to '/root/ray_results/objective_2026-06-16_19-34-53' in 0.0056s.

Trial objective_72905_00002 started with configuration:
+--------------------------------------------+
| Trial objective_72905_00002 config         |
+--------------------------------------------+
| lr                                     0.1 |
+--------------------------------------------+

Trial objective_72905_00002 completed after 1 iterations at 2026-06-16 19:35:14. Total running time: 20s
+------------------------------------------------+
| Trial objective_72905_00002 result             |
+------------------------------------------------+
| checkpoint_dir_name                            |
| time_this_iter_s                       0.00054 |
| time_total_s                           0.00054 |
| training_iteration                           1 |
| score                                   0.0081 |
+------------------------------------------------+

Trial status: 3 TERMINATED
Current time: 2026-06-16 19:35:14. Total running time: 20s
Logical resource usage: 1.0/2 CPUs, 0/0 GPUs
+----------------------------------------------------------------------------------+
| Trial name              status          lr     iter     total time (s)     score |
+----------------------------------------------------------------------------------+
| objective_72905_00000   TERMINATED   0.001        1        0.00133657    8.1e-05 |
| objective_72905_00001   TERMINATED   0.01         1        0.000440836   0       |
| objective_72905_00002   TERMINATED   0.1          1        0.000538349   0.0081  |
+----------------------------------------------------------------------------------+

{'lr': 0.01}